Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Uri: 127.0.0.1:27017
            Calls:
                - [selectDatabase, null]

Entity:
    Database: Webiny
    Attributes:
        many2many: \Apps\Webiny\Php\DevTools\Entity\Attributes\Many2ManyAttribute